//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://hsfl.ceho5518.vs.server.ConcreatService.ServerDiscovery", ConfigurationName = "IServerDiscoveryService")]
public interface IServerDiscoveryService {

    [System.ServiceModel.OperationContractAttribute(Action = "http://hsfl.ceho5518.vs.server.ConcreatService.ServerDiscovery/IServerDiscoverySe" +
        "rvice/Connect", ReplyAction = "http://hsfl.ceho5518.vs.server.ConcreatService.ServerDiscovery/IServerDiscoverySe" +
        "rvice/ConnectResponse")]
    void Connect(string message);

    [System.ServiceModel.OperationContractAttribute(Action = "http://hsfl.ceho5518.vs.server.ConcreatService.ServerDiscovery/IServerDiscoverySe" +
        "rvice/Connect", ReplyAction = "http://hsfl.ceho5518.vs.server.ConcreatService.ServerDiscovery/IServerDiscoverySe" +
        "rvice/ConnectResponse")]
    System.Threading.Tasks.Task ConnectAsync(string message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServerDiscoveryServiceChannel : IServerDiscoveryService, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServerDiscoveryServiceClient : System.ServiceModel.ClientBase<IServerDiscoveryService>, IServerDiscoveryService {

    public ServerDiscoveryServiceClient() {
    }

    public ServerDiscoveryServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName) {
    }

    public ServerDiscoveryServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress) {
    }

    public ServerDiscoveryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress) {
    }

    public ServerDiscoveryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress) {
    }

    public void Connect(string message) {
        base.Channel.Connect(message);
    }

    public System.Threading.Tasks.Task ConnectAsync(string message) {
        return base.Channel.ConnectAsync(message);
    }
}